exports.appString = {
  USER_CREATED: "User registered successfully",
  LOGIN_SUCCESS: "Login successful",
  INVALID_CREDENTIALS: "Invalid credentials",
  LOGOUT_SUCCESS: "Logged out successfully",
  USER_UPDATED: "User updated successfully",
  USER_DELETED: "User Soft deleted successfully",
  REGISTRATION_FAILED: "Registration Failed",
  Required_EmailPass: "emailId and password are required",
  LOGIN_FAILED: "Login failed",
  NOT_FOUND: "User not found",
  SUCCESS: "SUCCESS",
  USER_LOGOUT: "user logout successfully",
  LOGIN_FIRST: "Please Login First",
  USER_FILE_UPLOADED: "File Uploaded Successfully",
  USER_FILE_INVALID: "File is Invalid",
  img_ERR: "Only image files are allowed!",
  jWTNOT_DEFINED: "JWT secrets not defined",
  TOKEN_EXPIRED: "Invalid or expired token",
  TOKEN_MISSING: "Token missing",
  ALREDY_EXIST: "Already Exists",
  ADDRESS_CREATED: "User Address Created Successfully",
  ADDRESS_FAILED: "failed to create user address",
  ANOT_FOUND: "Address Not Found",
  PRIMARY_ADDRESS_UPDATED: "Primary Address Updated Successfully",
  ADDRESS_REQUIRED: "Address is required",
  LONG: " must be at least 4 characters long",
  LIMIT: "Address cannot exceed 20 characters",
  USERNAME_REQUIRED: "Username is required",
  EMAIL_REQUIRED: "EMAIL is required",
  ADMIN_CREATED: "Admin Created Successfully",
  ADMINALREDY_REGISTER: "Admin is already registered",
  ADMINACCESS_DEINED: "Admin access denied",
  RETRIVE: "User list retrieved successfully",
  Unauthorized: "User ID not found in token",
  Forbidden: "Admin access required",
  Forbidden1: "User record not found",
  SESSIONEXPIRED: "Session expired or logged in from another device",
  AUTHORIZATIONHEADERS: "Authorization header must start with Bearer",
  INVALIDREFRESHTOKEN: "Invalid refresh token",
  REFRESHREQUIRED: "Refresh token required",
  CHANGEPASSWORD: "Password changed successfully",
  INCORRECTPASSWORD: "Old password incorrect",
  RESETOTP: "Reset OTP",
  SENTOTP: "OTP sent to email",
  EXPIREDOTP: "expired OTP",
  RESETOTPSUCCESS: "Password reset successfully",
  DOESNOTMATCH: "New password and confirm password do not match",
  SERVICEUNAVAILABLE: "Email service unavailable",
  SMTPERROR: "SMTP Error",
  SENTSUCCESSFULLY: "Email sent successfully",
  CANNOTREACTIVATE: "Cannot reactivate: This user deleted their own account.",
  USERLISTRETRIVE: "User list retrieved successfully",
  INACTIVE: "User record not found or already inactive",
  REACTIVATE: "User reactivated successfully",
  INVALIDUSERID: "Invalid User ID format",
  ALREDYUSEPASSWORD:
    "This password was already used by you. Please choose a different one.",
  DELETDBYUSER: "Your account has been deleted by you. You cannot log in again",
  DELETEDBYADMIN:
    "Your account is deactivated by an admin. Please contact support",
  LOGOUT_FAILED: "lOGOUT FAILED SUCCESSFULLY",
  PARENTCATEGORY: "Parent category not found",
  SUBCATEGORYSUCCESS: "Subcategory created successfully",
  CATEGORYSUCCESS: "Category created successfully",
  CATEGORYFECTH: "Categories  fetched successfully",
  SUBCATEGORYNOTFOUND: "Subcategory not found",
  CATEGORYNOTFOUND: "Category name not found",
};
